### PR TITLE
Use Prettier

### PR DESCRIPTION
**Pull request by imbsky**
Overall it seems good.

### CODE REVIEW

**Comment by imbsky** [comment]
Should we ignore some files such as Forestry config files (`.forestry/*`) and `_articles/api/v*.md`?

**Comment by imbsky** [comment]
Oh I understood Forestry...
It seems a little complicated to use Prettier in this project.
But, if we don't do anything, the style will not be unified.
And we're in 2018.

**Comment by imbsky** [comment]
Resolved all conflicts.
I will commit the formatted files when you guys are ready to merge it.

**Comment by imbsky** [comment]
@zoltan-baba @erosdome Any progress?

**Comment by imbsky** [comment]
@zoltan-baba @erosdome Any updates?

**Comment by simonmarton** [comment]
@imbsky please resolve the conflicts, and we will merge it. Thank you! ✨

**Comment by imbsky** [comment]
@simonmarton Done! If you ready, I will format all markdown and yaml files.

**Pull request merged**
