### PR TITLE
Update most-important-concepts.md

### PR DESCRIPTION
**Pull request by chooblarin**
Fixed broken links (because this is *most important concepts*).

### CODE REVIEW

**Comment by viktorbenei** [comment]
> because this is most important concepts

I definitely agree :D

That said, the links you added are not up to date / not the right ones. The `/docs/` ones were for our old devcenter - the new/current one is at http://devcenter.bitrise.io and the `/docs/` links are 404

Did I miss something @chooblarin ?

**Comment by viktorbenei** [comment]
Ahh, ok, I think I know what happened here - you did check the docs on GitHub, not at http://devcenter.bitrise.io

The `/docs/` links should work on GitHub indeed, but we need the original ones, without `/docs/` for http://devcenter.bitrise.io

**Comment by viktorbenei** [comment]
I'll close this PR, but feel free to comment @chooblarin and if required I'll reopen it.

For the devcenter in general, I'd suggest you to browse it at http://devcenter.bitrise.io - if you'd find any issue there, every page has a directly GitHub link on it, so you can quickly jump to the related github view/edit page.

screen_shot_2017-04-13_at_16_01_47


If you have any question just let us know! ;)

**Comment by chooblarin** [comment]
Oh, I see. That was my misunderstanding. I didn't know about [http://devcenter.bitrise.io](http://devcenter.bitrise.io). 
Thank you for your reply!

**Comment by viktorbenei** [comment]
No problem at all @chooblarin :)

**Pull request closed without merging**
