### PR TITLE
Translate status reporting into Japanese

### PR DESCRIPTION
**Pull request by satoshi-takano**
Thanks for your review before. (#331, #340)
I also translated status-reporting.md into Japanese. Could you please review it?

### CODE REVIEW

**Comment by zoltan-baba** [comment]
Thanks once again! We really appreciate the contribution! I've merged it - thanks once more!

**Comment by satoshi-takano** [comment]
Thanks for your review again. By the way, can I already get a T-shirt? 👕

**Comment by zoltan-baba** [comment]
But of course! You'll definitely get a T-shirt, we'll be in touch with the details!

**Comment by satoshi-takano** [comment]
Thank you so much! I'm looking forward to get it 😆.

**Pull request merged**
