### PR TITLE
docker - how we build our images

### PR DESCRIPTION
**Pull request by viktorbenei**

### CODE REVIEW

**Comment by viktorbenei** [comment]
Note: share the docker socket as a volume, for web projects, or add a section to explain this.

**Comment by RyogaK** [comment]
It seems fine for me!

**Comment by tobrun** [comment]
I went through the docs and was able to get everything installed. Great job!

**Comment by viktorbenei** [comment]
Thanks for the feedback @tobrun - we'll merge this soon! ;)

**Pull request merged**
