### PR TITLE
Translate README into Japanese

### PR DESCRIPTION
**Pull request by helptan**
I've translated README.md to Japanese
Please see 😃

### CODE REVIEW

**Comment by imbsky** [comment]
It's better to use the word `段落` instead of `パラグラフ`.

**Comment by zoltan-baba** [comment]
Hi! Thanks for your effort. However, we wouldn't like to swap the English README.md file for a Japanese one - after all, for this project, we need users who do speak English :) But if you could put the Japanese translation under the English text, that would be great!

**Comment by imbsky** [comment]
That makes sense.

**Comment by helptan** [comment]
@zoltan-baba @imbsky 
Thanks for review!
I fix it!

**Comment by zoltan-baba** [comment]
Excellent job, thank you!

**Pull request merged**
